FlaUI/FlaUI.WebDriver

src/FlaUI.WebDriver.UITests/WebDriverFixture.cs
Using relative paths in code can sometimes introduce issues, especially if the location of the files relative to the executing code changes. It can make the code less portable and more prone to breaking if moved to a different location or if the directory structure changes.
I for example had an issue running the project in debug mode since it was going to the release folder.
this change worked for me on both configurations: Debug and Release
=> chore: Remove relative path from webDriverPath

.github/workflows/build.yml
Commit 14b22b24669991c611c7198ec7ace54fd4125e26 added creating a release on new tags, but the `build` job filter has no trigger on pushed tags.
=> Test run build on pushing tags

.github/workflows/build.yml
Commit 71a5cebdb715313e4250f34587f786ff25af8c5e removed `pull_request` from the build workflow, but that should not have been done.
=> Run build on pull requests

src/FlaUI.WebDriver.UITests/ActionsTest.cs
Added SetUp and TearDown Attributes
Moved the active element text one step earlier for easier debugging
=> test: ActionsTests improvements

src/FlaUI.WebDriver.UITests/TestUtil/TestApplication.cs
Added a more clever way to get the WpfApplication path by removing the usage of the relative path which is not recommended
=> Avoid using relative path for WpfApplication

README.md, src/FlaUI.WebDriver.UITests/FindElementsTests.cs, src/FlaUI.WebDriver/Controllers/FindElementsController.cs
=> Support X-Path selectors

src/FlaUI.WebDriver.UITests/ActionsTest.cs, src/FlaUI.WebDriver/Action.cs, src/FlaUI.WebDriver/Controllers/ActionsController.cs, src/FlaUI.WebDriver/Models/ActionItem.cs, src/FlaUI.WebDriver/Models/StringOrDictionaryConverter.cs
This allows `Actions.MoveToElement()` and `Actions.MoveByOffset` to work.
Added a pair of failing tests, and then a commit which fixes them.
https://www.w3.org/TR/webdriver2/#dfn-get-coordinates-relative-to-an-origin
Referenced https://github.com/appium/appium-uiautomator2-server/blob/master/app/src/main/java/io/appium/uiautomator2/utils/w3c/ActionsTokenizer.java#L307 for implementation
=> Support `origin` property in actions.

src/FlaUI.WebDriver.UITests/ElementTests.cs, src/FlaUI.WebDriver/Controllers/ElementController.cs, src/TestApplications/WpfApplication/MainWindow.xaml
https://www.w3.org/TR/webdriver2/#get-element-text says about this:
> Let rendered text be the result of performing implementation-specific steps whose result is exactly
> the same as the result of a Function.[[Call]](null, element) with bot.dom.getVisibleText as the this value.
Because it's implementation-defined, FlaUI.WebDriver's currently behavior is technically correct, however I feel the behavior from WinAppDriver is more useful. This PR tries to emulate that behavior by looking for various implemented patterns and using those to get the text value.
Tested against WinAppDriver's behavior and seems to match so far, with one exception noted in the comments.
=> Make Get Element Text match WinAppDriver more closely.

src/FlaUI.WebDriver.UITests/SessionTests.cs, src/FlaUI.WebDriver/Controllers/SessionController.cs, src/FlaUI.WebDriver/Session.cs
When a session finishes or times out, don't close the app if the session was attached to an existing app using `appTopLevelWindow` or `appTopLevelWindowTitleMatch`.
This feels like intuitive behavior to me: the app was running before the session started so one can assume that the user is in control of the app lifetime.
Added a commit with failing tests, and a commit with a simple fix.
=> On session close, don't close apps that weren't started by the WebDriver

README.md, src/FlaUI.WebDriver.UITests/ElementTests.cs, src/FlaUI.WebDriver/AutomationElementExtensions.cs, src/FlaUI.WebDriver/Controllers/ElementController.cs
Implements `/session/{session id}/element/{element id}/attribute/{name}`.
Not so crazy about using reflection here, but it seems it's the only way to get the property ID from a string?
Fixes #25
=> Implement Get Element Attribute.

README.md, src/FlaUI.WebDriver.UITests/WindowTests.cs, src/FlaUI.WebDriver/Controllers/WindowController.cs
Not sure what you'll think about this one but this PR reinstates the use of `GetAllTopLevelWindows`. This was removed due to https://github.com/FlaUI/FlaUI/issues/596, which I would like to investigate, however I've so far been unable to repro the issue. Maybe if the failing code path is enabled then I'll hit it and will be able to investigate.
Also, I need to be able to retrieve all open window handles, so only returning the main window and modal windows is a problem for me...
=> Reinstate usage of GetAllTopLevelWindows.

src/FlaUI.WebDriver.UITests/FindElementsTests.cs, src/FlaUI.WebDriver/Controllers/FindElementsController.cs
Do not throw a NoSuchElementException when the result of Find elements is an empty list, as per the spec. Closes #34.
=> Return empty list from Find elements

src/FlaUI.WebDriver.UITests/ElementTests.cs, src/FlaUI.WebDriver.UITests/TestUtil/TestApplication.cs, src/FlaUI.WebDriver.UITests/WindowTests.cs, src/FlaUI.WebDriver/FlaUI.WebDriver.csproj, src/FlaUI.WebDriver/app.manifest, src/TestApplications/WpfApplication/MainWindow.xaml, src/TestApplications/WpfApplication/MainWindow.xaml.cs, src/TestApplications/WpfApplication/WpfApplication.csproj, src/TestApplications/WpfApplication/app.manifest
This PR makes the WebDriver process DPI scaling aware. If this is not done then capturing screenshots [will not work on monitors with scaling other than 100%](https://github.com/FlaUI/FlaUI/issues/359) and sometimes [element positioning is miscalculated](https://github.com/FlaUI/FlaUI/issues/306).
It also makes the test application DPI-aware as it needs to communicate the current scaling factor to the unit tests. The test application exposes its current DPI scaling in the status bar, and this is read in tests that require checking bounds/positions.
Note that WinAppDriver is also DPI aware so this should also help match the behavior there.
=> Make WebDriver DPI scaling-aware.

src/FlaUI.WebDriver.UITests/FindElementsTests.cs, src/FlaUI.WebDriver/ISessionRepository.cs, src/FlaUI.WebDriver/KnownElement.cs, src/FlaUI.WebDriver/KnownWindow.cs, src/FlaUI.WebDriver/Session.cs, src/FlaUI.WebDriver/SessionCleanupService.cs, src/FlaUI.WebDriver/SessionRepository.cs
Evict unavailable elements to prevent COM exceptions and to free memory. See https://github.com/FlaUI/FlaUI.WebDriver/issues/35. The COM exceptions from a growing set of unavailable elements may be the cause of degrading performance as well.
=> Evict unavailable elements and improve element compare performance

src/FlaUI.WebDriver/Controllers/ActionsController.cs, src/FlaUI.WebDriver/InputState.cs
The spec is unclear on when input sources should be added to the input source map. Previously it was being done in `ExtractActionSequence` but the problem with doing it there is that there's no way to know if `GetOrCreateInputSource` is returning an existing input source or creating a new one, causing #43.
Move the logic to add an input source to `GetOrCreateInputSource` to fix  this.
(It would kinda make sense to do it instead in `CreateInputSource` but the spec defines callers of this method which add the input source manually :/ )
Fixes #43
=> Add input sources in GetOrCreateInputSource

src/FlaUI.WebDriver/KnownElement.cs, src/FlaUI.WebDriver/KnownWindow.cs, src/FlaUI.WebDriver/Session.cs
Prevent stale enumerators while evicting unavailable elements or windows. Closes #42.
=> Thread safe adding and evicting of elements

src/FlaUI.WebDriver.UITests/SessionTests.cs, src/FlaUI.WebDriver/Controllers/SessionController.cs, src/FlaUI.WebDriver/MergedCapabilities.cs
Use very specific error messages to indicate capability mismatches. Closes #26.
=> Better capability matching errors

src/FlaUI.WebDriver/Controllers/ElementController.cs
Avalonia 11.0.x does not currently implement this property: I will add it soon to Avalonia but in the meantime check that the property is supported before trying to read it. WinAppDriver seemed to handle this case so FlaUI.WebDriver also should.
=> Check that IsOffscreen is supported before trying to use it.

src/FlaUI.WebDriver.UITests/FindElementsTests.cs, src/FlaUI.WebDriver/Controllers/FindElementsController.cs
=> Add ability to find desktop elements

.github/dependabot.yml
Attempt to fix dependabot, which is running daily but does not discover any projects:
```
No dotnet-tools.json file found.
No global.json file found.
Discovering projects beneath [.].
No project files found.
Central Package Management is not enabled.
```
=> Fix dependabot directory

.github/workflows/build.yml, src/FlaUI.WebDriver.UITests/FlaUI.WebDriver.UITests.csproj, src/FlaUI.WebDriver/FlaUI.WebDriver.csproj, src/TestApplications/WpfApplication/WpfApplication.csproj
Update because .NET 8 is the latest LTS, released November 2023 (see https://dotnet.microsoft.com/en-us/platform/support/policy).
FlaUI itself is .NET 6-based still, but can be used from .NET 8 projects: https://github.com/FlaUI/FlaUI/issues/611.
=> Update to .NET 8 🎉

src/FlaUI.WebDriver/Controllers/ElementController.cs
Ignore exception on scrolling into view of an element before element click or element send keys.
Closes #75.
=> Ignore exception on scrolling element into view

src/FlaUI.WebDriver.UITests/SessionTests.cs, src/FlaUI.WebDriver/Controllers/SessionController.cs
Instead of returning 'session not created' when not all capabilities were matched, ignore not matching capabilities. I am not sure whether this is to the letter of the standard, but it will not do much harm except for users that may be surprised if FlaUI.WebDriver just ignores their supplied capability which is not implemented for FlaUI.WebDriver yet.
Fixes #100.
=> Ignore not matched capabilities

README.md, src/FlaUI.WebDriver/Controllers/ExecuteController.cs, src/FlaUI.WebDriver/Models/WindowsHoverScript.cs, src/FlaUI.WebDriver/Models/WindowsScrollScript.cs, src/FlaUI.WebDriver/Services/IWindowsExtensionService.cs, src/FlaUI.WebDriver/Services/WindowsExtensionService.cs
Add the `windows: scroll` extension script for compatibility with appium-windows-driver.
Document the other Windows extension scripts and throw on unsupported options. Also fix the calculation of the mouse position by element ID and x and y coordinates.
=> Add scroll script and fix other Windows extensions
